language: node_js

dist: focal

addons:
  chrome: stable


node_js:
  - 14
  - 16
  - 18

jobs:
  allow_failures:
    - node_js: 18

script: pnpm run quickstart && pnpm run test

notifications:
  email:
    recipients:
      - sdk_developers@cloudinary.com
