/**
 * @mixin SvelteSDK
 * @description The Coudinday Svelte SDK contains components like <AdvancedImage> to easily render your media assets from Cloudinary.
 * The SDK also comes with support for optional js plugins that make the components smart, with features like lazy loading, placeholder, accessibility & responsiveness
 *
 * @example
 * <caption>
 *  Please note that the order of the plugins is important. See home for more details.
 * </caption>
 * // Example
 *
 * <script>
 *
 * import {CloudinaryImage} from '@cloudinary/base';
 * import { AdvancedImage, accessibility, responsive, lazyload, placeholder } from '@cloudinary/svelte';
 *
 * const img = new CloudinaryImage('sample', {cloudName: 'demo'});
 *
 * // Close script tag
 * </scr\ipt>
 *
 * <AdvancedImage cldImg={img} plugins={[lazyload(),responsive(), accessibility(), placeholder()]}/>
 *
 */

/**
 * @memberOf SvelteSDK
 * @type {Component}
 * @description The Cloudinary image component
 * @prop {CloudinaryImage} cldImg Generated by @cloudinary/base
 * @prop {Plugins} plugins Advanced image component plugins accessibility(), responsive(), lazyload(), placeholder()
 */
class AdvancedImage{}