<template>
  <img v-if="isBrowser()" ref="imageRef" />
  <img v-else src="{{getSsrSrc()}}" />
</template>

<script setup lang="ts">
/**
 * @memberOf Vue3SDK
 * @type {Component}
 * @description The Cloudinary image component.
 * @prop {CloudinaryImage} cldImg Generated by @cloudinary/url-gen
 * @prop {Plugins} plugins Advanced image component plugins accessibility(), responsive(), lazyload(), placeholder()
 */

import { defineProps, ref, onMounted, onUpdated, onUnmounted } from "vue";
import { CloudinaryImage } from "@cloudinary/url-gen/assets/CloudinaryImage";
import {
  HtmlImageLayer,
  isBrowser,
  serverSideSrc,
  cancelCurrentlyRunningPlugins,
  Plugins,
} from "@cloudinary/html";
import { SDKAnalyticsConstants } from "../internal/SDKAnalyticsConstants";

interface ImgProps {
  cldImg: CloudinaryImage;
  plugins?: Plugins;

  [x: string]: any;
}

const props = defineProps<ImgProps>();

const imageRef = ref(null);
let htmlLayerInstance;

const getSsrSrc = () => serverSideSrc(props.plugins, props.cldImg);

/**
 * On mount, creates a new HTMLLayer instance and initializes with ref to img element,
 * user generated cloudinaryImage and the plugins to be used.
 */
onMounted(() => {
  htmlLayerInstance = new HtmlImageLayer(
    imageRef.value,
    props.cldImg,
    props.plugins,
    SDKAnalyticsConstants
  );
});

/**
 * On update, we cancel running plugins and update image instance with the state of user
 * cloudinaryImage and the state of plugins.
 */
onUpdated(() => {
  cancelCurrentlyRunningPlugins(htmlLayerInstance.htmlPluginState);
  // call html layer to update the dom again with plugins and reset toBeCanceled
  htmlLayerInstance.update(props.cldImg, props.plugins, SDKAnalyticsConstants);
});

/**
 * On unmount, we cancel the currently running plugins.
 */
onUnmounted(() => {
  // Safely cancel running events on unmount.
  cancelCurrentlyRunningPlugins(htmlLayerInstance.htmlPluginState);
});
</script>
