<template>
  <video ref="videoRef" />
</template>

<script setup lang="ts">
/**
 * @memberOf VueSDK
 * @type {Component}
 * @description The Cloudinary video component.
 * @prop {CloudinaryVideo} cldVid Generated by @cloudinary/url-gen
 * @prop {VideoPoster} cldPoster Generated by @cloudinary/url-gen
 * @prop {Plugins} plugins Advanced video component plugins accessibility(), responsive(), lazyload(), placeholder()
 * @prop {VideoSources} sources Optional sources to generate
 * @example
 *  <caption>
 *  Using custom defined resources.
 * </caption>
 * <template>
 *   <AdvancedVideo :cldVid="cldVid" :sources="sources" controls width="600" />
 * </template>
 *
 * <script lang="ts">
 * import { defineComponent } from "vue";
 * import { auto } from "@cloudinary/url-gen/qualifiers/videoCodec";
 * import { videoCodec } from "@cloudinary/url-gen/actions/transcode";
 * import { AdvancedVideo } from "../dist";
 * import { CloudinaryVideo } from "@cloudinary/url-gen/assets/CloudinaryVideo";
 *
 * export default defineComponent({
 *   name: "App",
 *   components: {
 *     AdvancedVideo,
 *  },
 *   setup(props) {
 *     const cldVid = new CloudinaryVideo(
 *       "dog",
 *       { cloudName: "demo" },
 *       { analytics: false }
 *     );
 *
 *     const sources = [
 *       {
 *         type: "mp4",
 *         transcode: videoCodec(auto()),
 *       },
 *       {
 *         type: "webm",
 *         transcode: videoCodec(auto()),
 *       },
 *     ];
 *
 *     return {
 *       cldVid,
 *       sources,
 *     };
 *   },
 * });
 * </script>
 * 
 * 
 */

import { ref, onMounted, onUpdated, onUnmounted } from "vue";
import { CloudinaryVideo } from "@cloudinary/url-gen";
import {
  HtmlVideoLayer,
  Plugins,
  VideoPoster,
  VideoSources,
  cancelCurrentlyRunningPlugins,
} from "@cloudinary/html";

interface VideoProps {
  cldVid: CloudinaryVideo;
  plugins?: Plugins;
  sources?: VideoSources;
  cldPoster?: VideoPoster;

  [x: string]: any;
}

// Disabled linting due to [@vue/compiler-sfc] `defineProps` is a compiler macro and no longer needs to be imported.
// eslint-disable-next-line no-undef
const props = defineProps<VideoProps>();

const videoRef = ref(null);
let htmlLayerInstance;

/**
 * On mount, creates a new HTMLLayer instance and initializes with ref to img element,
 * user generated cloudinaryVideo and the plugins to be used.
 */
onMounted(() => {
  htmlLayerInstance = new HtmlVideoLayer(
    videoRef.value,
    props.cldVid,
    props.sources,
    props.plugins,
    undefined,
    props.cldPoster
  );
});

/**
 * On update, we cancel running plugins and update image instance with the state of user
 * cloudinaryVideo and the state of plugins.
 */
onUpdated(() => {
  cancelCurrentlyRunningPlugins(htmlLayerInstance.htmlPluginState);
  // call html layer to update the dom again with plugins and reset toBeCanceled
  htmlLayerInstance.update(
    props.cldVid,
    props.sources,
    props.plugins,
    undefined,
    props.cldPoster
  );
});

/**
 * On unmount, we cancel the currently running plugins.
 */
onUnmounted(() => {
  // Safely cancel running events on unmount.
  cancelCurrentlyRunningPlugins(htmlLayerInstance.htmlPluginState);
});
</script>
