<template>
  <video ref="videoRef" />
</template>

<script setup lang="ts">
// import { defineComponent } from "vue";

// export default defineComponent({
//   name: "AdvancedVideo",
//   props: {
//     url: String,
//   },
// });

/**
 * @memberOf CloudinaryVueSDK
 * @type {Component}
 * @description The Cloudinary video component.
 * @prop {CloudinaryVideo} cldVid Generated by @cloudinary/url-gen
 * @prop {Plugins} plugins Advanced video component plugins accessibility(), responsive(), lazyload(), placeholder()
 */

import { ref, onMounted, onUpdated, onUnmounted } from "vue";
import { CloudinaryVideo } from "@cloudinary/url-gen/assets/CloudinaryVideo";
import {
  HtmlVideoLayer,
  Plugins,
  VideoSources,
  cancelCurrentlyRunningPlugins,
} from "@cloudinary/html";
import { SDKAnalyticsConstants } from "../internal/SDKAnalyticsConstants";

interface VideoProps {
  cldVid: CloudinaryVideo;
  plugins?: Plugins;
  sources?: VideoSources;

  [x: string]: any;
}

// Disabled linting due to [@vue/compiler-sfc] `defineProps` is a compiler macro and no longer needs to be imported.
// eslint-disable-next-line no-undef
const props = defineProps<VideoProps>();

const videoRef = ref(null);
let htmlLayerInstance;

/**
 * On mount, creates a new HTMLLayer instance and initializes with ref to img element,
 * user generated cloudinaryVideo and the plugins to be used.
 */
onMounted(() => {
  htmlLayerInstance = new HtmlVideoLayer(
    videoRef.value,
    props.cldVid,
    props.sources,
    props.plugins
    // SDKAnalyticsConstants
  );
});

/**
 * On update, we cancel running plugins and update image instance with the state of user
 * cloudinaryVideo and the state of plugins.
 */
onUpdated(() => {
  cancelCurrentlyRunningPlugins(htmlLayerInstance.htmlPluginState);
  // call html layer to update the dom again with plugins and reset toBeCanceled
  htmlLayerInstance.update(props.cldVid, props.plugins, SDKAnalyticsConstants);
});

/**
 * On unmount, we cancel the currently running plugins.
 */
onUnmounted(() => {
  // Safely cancel running events on unmount.
  cancelCurrentlyRunningPlugins(htmlLayerInstance.htmlPluginState);
});
</script>
